### ISSUE TITLE
Questions about Sandbox

### ISSUE THREAD

**Issue by marcus302** [Ingenico-ePayments/connect-sdk-python3#4]
I've been experimenting with the [sandbox](https://epayments-api.developer-ingenico.com/s2sapi/v1/en_US/java/environments.html?paymentPlatform=GLOBALCOLLECT) and have two questions:

- After approving a payment, its status remains on "CAPTURE_REQUESTED". Shouldn't the sandbox set this to "PAID" to simulate payments, as described [here](https://github.com/Ingenico-ePayments/connect-sdk-php/issues/3)? This doesn't happen for me.
- I've tried creating a payout, thinking I might not need "paid" payments to test this. When I try to do this, I get an error that my merchant ID is not authorized for payouts. Am I right in thinking that this isn't possible in the sandbox?

Any description of the capabilities and limits of the sandbox would be greatly appreciated. (An explanation of my mistake however, would be as well.)

In case somebody wants to dive into this, you can find my code [here](https://github.com/Spheer-ai/worldline-poc).

**Comment by IngenicoEPayments** [comment]
Hello Mark,

Thank you for contacting us.
These questions are regarding the environment itself rather than the SDK and the usage thereof.

If possible, please contact the Merchant Services team or your Implementation Manager for more information.

Otherwise you could seek help through the [official support channels](https://worldline.com/en/home/main-navigation/git.html) or documentation on the Worldline developer documentation at https://docs.connect.worldline-solutions.com/.

Kind Regards,
Worldline Connect SDK Support
